export const DELETE_PACKAGE = 'DELETE_PACKAGE';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const DELETE_COLLECTIONS = 'DELETE_COLLECTIONS';
export const SET_LOADING = 'SET_LOADING';
export const TOAST_SUCCESS = 'TOAST_SUCCESS';
export const TOAST_ERROR = 'TOAST_ERROR';
